# Generated by Django 3.2.16 on 2023-01-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id_otm',
        ),
    ]
