# Generated by Django 3.2.16 on 2023-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_remove_libro_autor_id_otm'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
