# Generated by Django 3.2.16 on 2023-01-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_autor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
    ]
