# Generated by Django 3.2.16 on 2023-01-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_remove_libro_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
            preserve_default=False,
        ),
    ]
