# Generated by Django 3.2.16 on 2023-01-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_auto_20230105_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
    ]
